import type { Metadata } from 'next'
import satoshiFont from 'next/font/local'
import React from 'react'
import './globals.css'

const satoshiRegular = satoshiFont({
  src: '../../public/fonts/Satoshi-Regular.woff2',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={satoshiRegular.className}>{children}</body>
    </html>
  )
}
